sidebar:
  menu:
    index: '[首页](/index/)'
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    # notes: '[笔记](/notes/)'
    # more: '[更多](/more/)'
  # logo:
  #  title: '[<img no-lazy height="32px" src="https://blog-alan.oss-cn-hangzhou.aliyuncs.com/hexo_blog/CubikLogo.png"/>](/)'

comments:
  service: beaudar
  beaudar:
    repo: alanosy/blog-comments