sidebar:
  menu:
    index: '[首页](/index/)'
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/wiki/)'
    # notes: '[笔记](/notes/)'
    # more: '[更多](/more/)'
comments:
  service: beaudar
  beaudar:
    repo: alanosy/blog-comments